apiVersion: v1
kind: Service
metadata:
  name: my-tomcat-service
spec:
  type: NodePort # Exposes the service on each Node's IP at a static port
  selector:
    app: my-tomcat-app # Must match the labels of the Pods (from Deployment)
  ports:
    - protocol: TCP
      port: 80         # Port the service will be available on *within* the cluster
      targetPort: 8080 # Port the container (Tomcat) is listening on
      # nodePort: 30080 # Optional: if not specified, K8s assigns a port in 30000-32767 range
                      # Let's pick one to be predictable, e.g., 30088
      nodePort: 30088
